project:
  type: website

website:
  title: "Random Randomness"
  image: "cover.jpg"
  navbar:
    left:
      - href: ai.qmd
        text: AI

      - href: coding.qmd
        text: CODING

      - href: health.qmd
        text: HEALTH

      - href: index.qmd
        text: OTHER
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



